package fun.fengwk.chatjava.core.client.response;

import lombok.Data;

/**
 * @author fengwk
 */
@Data
public class ChatToolCallFunction {

    /**
     * The name of the function to call.
     */
    private String name;

    /**
     * The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
     */
    private String arguments;

}
