package fun.fengwk.chatjava.core.client.response;

import fun.fengwk.chatjava.core.client.request.ChatMessage;
import lombok.Data;

/**
 * @author fengwk
 */
@Data
public class ChatChoice {

    /**
     * The reason the model stopped generating tokens. This will be stop if the model hit a natural stop point or a provided stop sequence, length if the maximum number of tokens specified in the request was reached, content_filter if content was omitted due to a flag from our content filters, tool_calls if the model called a tool, or function_call (deprecated) if the model called a function.
     */
    private String finish_reason;

    /**
     * The index of the choice in the list of choices.
     */
    private Integer index;

    /**
     * A chat completion message generated by the model.
     */
    private ChatMessage message;

    /**
     * for stream api
     */
    private ChatMessage delta;

    /**
     * Log probability information for the choice.
     */
    private ChatLogprobs logprobs;

}
